### ISSUE TITLE
Order not delivered

### ISSUE THREAD

**Issue by vihaanmisra** [Akashsingh310/OpenKart#1]
I placed an order for the Apple MacBook Pro on your website, haven't yet received the shipment. Please deliver it as soon as possible.

**Comment by Akashsingh310** [comment]
Sure sure we will  looking forward to it
Thankyou for your feedback
                     -Team Openkart

**Comment by vihaanmisra** [comment]
Do not just look forward to it, please take action and deliver the laptop to me as soon as possible.

**Comment by Akashsingh310** [comment]
Sure, we will do that. 😁😁😁

**Comment by vihaanmisra** [comment]
Good.

**Comment by Akashsingh310** [comment]
😂😂😂
